SenzaInfo:
  StackName: kewan
  Parameters:
    - DockerImage:
        Description: "Docker image path with version tag of kewan."
    - MintBucket:
        Description: "Mint Bucket of kewan."
    - ScalyrAccountKey:
        Description: "Scalyr Account Key, necessary for Logging."
    - ApplicationID:
        Description: "The Application Id which got registered for kewan in Yourturn/Kio."
SenzaComponents:
  - Configuration:
      Type: Senza::StupsAutoConfiguration
  - AppServer:
      Type: Senza::TaupageAutoScalingGroup
      AutoScaling:
        Minimum: 3
        Maximum: 3
        MetricType: CPU
      InstanceType: t2.micro
      HealthCheckType: EC2
      SecurityGroups:
        - "Fn::GetAtt" : [ "KewanSecGroup" , "GroupId" ]
      IamRoles:
        - Ref: KewanRole
      TaupageConfig:
        application_id: "{{Arguments.ApplicationID}}"
        runtime: Docker
        source: "{{Arguments.DockerImage}}"
        ports:
          2181: 2181
          2888: 2888
          3888: 3888
        networking: host
        mint_bucket: '{{Arguments.MintBucket}}'
        scalyr_account_key: '{{Arguments.ScalyrAccountKey}}'
Resources:
  KewanRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: AmazonS3MintBucketAccess
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action: "s3:GetObject"
            Resource: ["arn:aws:s3:::{{Arguments.MintBucket}}/*"]
      - PolicyName: AmazonEC2MetadataReadAccess
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action: ec2:Describe*
            Resource: "*"
          - Effect: Allow
            Action: autoscaling:Describe*
            Resource: "*"
  KewanSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Kewan Appliance Security Group"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2181
          ToPort: 2181
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 2888
          ToPort: 2888
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 3888
          ToPort: 3888
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
